# Use root/mysql as user/password credentials

version: '3.8'

services:
  python_apis:
    build:
      context: ./
      dockerfile: Dockerfile
    image: prueba-web-mel
    command: gunicorn entrypoint:app --bind 0.0.0.0:5000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    hostname: web
  
  vue:
    build:
      context: ./
      dockerfile: DockerfileVue
    image: vueapp:Mel
    container_name: "vue_app_container"
    volumes:
      - ./app_vue/:/app/
    ports:
      - "7000:8080"
      - "7001:8081"
  
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pochoclo
      MYSQL_DATABASE: wolfcampus_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - 4306:3306
      - 43060:33060
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    hostname: adminer

# volumes:
#   db_volume:
#   pgadmin-data:
